(()=>{'use strict';const D=window.CHINA_GUIDE,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let itinerary=localStorage.getItem('china-itinerary')||'nature',destination=null,view='overview';
const active=()=>D.itineraries[itinerary],destinations=()=>active().route.map(id=>[id,D.destinations[id]]);
function switcher(){heroSwitch.innerHTML=Object.values(D.itineraries).map(x=>`<button data-itinerary="${x.id}" class="${x.id===itinerary?'active':''}">${x.name}</button>`).join('');heroSwitch.querySelectorAll('button').forEach(b=>b.onclick=()=>{itinerary=b.dataset.itinerary;destination=null;localStorage.setItem('china-itinerary',itinerary);renderAll()})}
function overview(){const t=active();overviewTitle.textContent=t.short;overviewIntro.textContent=t.intro;heroSummary.innerHTML=t.stats.map(x=>`<span class="summary-pill"><b>${x[0]}</b>${x[1]}</span>`).join('');routeTrack.innerHTML=destinations().map(([id,d],i)=>`<button class="route-stop" data-dest="${id}" style="background-image:url('${d.image}')"><span><small>Tappa ${i+1}</small><b>${d.name}</b></span></button>`).join('');overviewStats.innerHTML=t.stats.map(x=>`<article class="stat-card"><span>${x[1]}</span><strong>${x[0]}</strong></article>`).join('');decisionCard.innerHTML=`<p class="eyebrow light">Prossima decisione</p><h3>Da definire prima delle prenotazioni</h3><p>${t.decision}</p>`;destinationPreview.innerHTML=destinations().map(([id,d])=>`<button class="destination-card" data-dest="${id}" style="background-image:url('${d.image}')"><p class="eyebrow light">${d.cn} · ${d.days}</p><h3>${d.name}</h3><p>${d.tagline}</p></button>`).join('');bindDestButtons()}
function days(){dayList.innerHTML=active().days.map(d=>{const place=D.destinations[d[1]];return `<article class="day-card"><div class="day-number">${d[0]}</div><div><p class="eyebrow">${place.name}</p><h3>${d[2]}</h3><p>${d[3]}</p></div><button data-dest="${d[1]}">Apri ${place.name}</button></article>`}).join('');bindDestButtons()}
function destTabs(){destination=destination&&active().route.includes(destination)?destination:active().route[0];destinationTabs.innerHTML=destinations().map(([id,d])=>`<button data-dest="${id}" class="${id===destination?'active':''}">${d.name}</button>`).join('');destinationTabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{destination=b.dataset.dest;renderDestination()})}
const list=(title,items)=>`<section class="guide-block"><h3>${title}</h3><ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul></section>`;
function renderDestination(){destTabs();const d=D.destinations[destination];destinationGuide.innerHTML=`<section class="destination-hero" style="background-image:url('${d.image}')"><div class="shell"><p class="eyebrow light">${d.cn} · ${d.days}</p><h2>${d.name}</h2><p class="destination-intro">${d.tagline}</p></div></section><div class="shell destination-layout"><div class="guide-sections">${list('Dove dormire',d.stay)}${list('Cosa mangiare',d.food)}${list('Ristoranti e come cercarli',d.restaurants)}${list('Attività e cose da vedere',d.activities)}${list('Come muoversi',d.transport)}${list('Consigli, errori e piano B',d.tips)}</div><aside class="destination-aside"><article class="aside-card"><p class="eyebrow light">Budget locale</p><h4>${d.cost}</h4><p>Stima indicativa per persona, escluso il volo internazionale.</p></article><article class="aside-card light"><p class="eyebrow">Nel viaggio</p><h4>${d.days}</h4><button class="link-button" data-view-jump="days">Apri i giorni</button></article><article class="aside-card light"><p class="eyebrow">Ricerca rapida</p><p>Copia il nome cinese per Amap, Dianping o il tassista.</p><strong>${d.cn}</strong></article></aside></div>`;destinationGuide.querySelector('[data-view-jump]')?.addEventListener('click',()=>setView('days'));window.scrollTo({top:0,behavior:'smooth'})}
function plan(){const t=active();budgetCard.innerHTML=`<div class="budget-total"><p class="eyebrow">Stima a persona</p><strong>${t.budget}</strong><p>${t.intro}</p></div><div class="budget-lines">${t.budgetLines.map(x=>`<div class="budget-line"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`;const cols=[['Da decidere',[t.decision,'Date definitive e aeroporti','Livello di comodità']],['Da prenotare',['Voli principali','Prime notti e ultime notti',...destinations().slice(0,3).map(x=>`Attività chiave · ${x[1].name}`)]],['Da ricontrollare',['Meteo e chiusure','Regole bagagli e power bank','Orari treni e indirizzi cinesi']]];bookingBoard.innerHTML=cols.map(c=>`<section class="booking-column"><h3>${c[0]}</h3>${c[1].map(x=>`<div class="booking-item">${x}<small>${itinerary==='classic'?'Itinerario classico':'Itinerario natura'}</small></div>`).join('')}</section>`).join('')}
function practical(){practicalGrid.innerHTML=D.practical.map(x=>`<article class="practical-card"><p class="eyebrow">${x[0]}</p><p>${x[1]}</p></article>`).join('');phraseGrid.innerHTML=D.phrases.map(x=>`<button class="phrase-card" data-copy="${x[1]}"><small>${x[0]}</small><strong>${x[1]}</strong></button>`).join('');phraseGrid.querySelectorAll('button').forEach(b=>b.onclick=()=>navigator.clipboard?.writeText(b.dataset.copy));checklist.innerHTML=D.checks.map((x,i)=>`<label class="check-item"><input type="checkbox" data-check="${i}"> ${x}</label>`).join('');const saved=JSON.parse(localStorage.getItem('china-checks')||'[]');checklist.querySelectorAll('input').forEach(i=>{i.checked=saved.includes(+i.dataset.check);i.onchange=()=>{const values=$$('#checklist input:checked').map(x=>+x.dataset.check);localStorage.setItem('china-checks',JSON.stringify(values))}})}
function drawerRender(){drawerContent.innerHTML=`<div class="drawer-route"><p class="eyebrow">Itinerario attivo</p><strong>${active().name}</strong></div>${destinations().map(([id,d])=>`<button data-dest="${id}">${d.name}<small> · ${d.days}</small></button>`).join('')}`;drawerContent.querySelectorAll('button').forEach(b=>b.onclick=()=>{destination=b.dataset.dest;closeDrawer();setView('destinations')})}
function setView(next){view=next;$$('.app-view').forEach(v=>v.hidden=v.id!==`${next}View`);$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===next));if(next==='destinations')renderDestination();if(next==='plan')plan();if(next==='practical')practical();window.scrollTo({top:next==='destinations'?destinationTabs.offsetTop-80:0,behavior:'smooth'})}
function bindDestButtons(){$$('[data-dest]').forEach(b=>b.onclick=()=>{destination=b.dataset.dest;setView('destinations')})}
function openDrawer(){drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');drawerBackdrop.hidden=false}function closeDrawer(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');drawerBackdrop.hidden=true}
function renderAll(){switcher();overview();days();destTabs();plan();practical();drawerRender();setView(view)}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));menuButton.onclick=openDrawer;closeDrawer.onclick=closeDrawer;drawerBackdrop.onclick=closeDrawer;renderAll()})();
