window.KOREA_TRIPS={
  week:{label:'7 giorni',sub:'Seoul + Busan',stats:[['7 giorni','ritmo compatto'],['2 città','Seoul · Busan'],['₩1.9–3.0M','a terra, in due'],['2 notti forti','Itaewon · Gwangalli']],route:'Seoul 4 notti → Busan 2 notti → ritorno. È la versione che tiene Itaewon Class al centro senza trasformare una settimana in una gara di stazioni.',budget:{total:'€1.200–1.850',rows:[['6 notti','€510–780'],['Cibo + serate','€420–630'],['Trasporti','€150–220'],['Attività','€120–220']]},days:[
    {n:1,place:'SEOUL · YEONNAM',title:'Atterrare dentro la città',desc:'Niente monumenti appena scesi dall’aereo: check-in tra Hongdae e Yeonnam, camminata nel quartiere e prima sera normale.',slots:[['Pomeriggio','AREX → Seoul, T-money/Climate Card, check-in.'],['Sera','Yeonnam-dong, Gyeongui Line Forest Park, cena in un locale piccolo.'],['Notte','Convenience store, coin noraebang o birra in un pub di quartiere.']],note:'Obiettivo: adattarsi al fuso e vedere subito una Seoul vissuta, non consumare attrazioni.'},
    {n:2,place:'ITAewon class',title:'La giornata DanBam',desc:'Baekbeom Plaza e mura di Namsan, Noksapyeong, i punti della serie e Itaewon quando si accende davvero.',slots:[['Mattina','Baekbeom Plaza → Namsan fortress wall, scena del bacio e skyline.'],['Pomeriggio','G Guesthouse → Angel Wings → Children’s Park → vicoli di Itaewon.'],['Tramonto + notte','Noksapyeong Overpass al blu dell’ora → Seoul Bam/DanBam → Haebangchon.']],note:'Questa giornata va fatta lenta e finita di notte. È il pezzo più “Itaewon Class” del viaggio.'},
    {n:3,place:'SEOUL · JONGNO',title:'Vecchia Seoul, poi strada',desc:'Palazzo sì, ma presto; poi Seochon, mercato, vicoli e una sera sotto i tendoni di Jongno/Euljiro.',slots:[['Mattina','Gyeongbokgung appena apre → Seochon a piedi.'],['Pomeriggio','Tongin/Gwangjang, Ikseon-dong, caffè o laboratorio breve.'],['Sera','Jongno 3-ga o Euljiro: pojangmacha, tavoli condivisi, secondo giro improvvisato.']],note:'Nei pojangmacha e nei piccoli bar è più naturale parlare con chi sta vicino rispetto ai locali patinati.'},
    {n:4,place:'SEOUL · MONTAGNA',title:'Fare qualcosa, non solo guardare',desc:'Mezza giornata attiva, poi bagno caldo e serata pop-coreana senza parco a tema.',slots:[['Mattina','Bukhansan: percorso breve/medio in base al meteo.'],['Pomeriggio','Jjimjilbang: docce, saune, sale comuni e snack.'],['Sera','Mangwon/Hongdae: barbecue, noraebang; KBO se c’è una partita.']],note:'Piano pioggia: Seongsu + PC bang + jjimjilbang, senza sprecare la giornata.'},
    {n:5,place:'SEOUL → BUSAN',title:'KTX e mare di notte',desc:'Il trasferimento è parte del viaggio: stazione, lunch box, arrivo a Busan e Gwangalli al tramonto.',slots:[['Mattina','KTX Seoul → Busan, circa 2h30–3h.'],['Pomeriggio','Check-in Seomyeon o Gwangan; passeggiata senza fretta.'],['Sera','Gwangalli: cena, spiaggia, Gwangan Bridge acceso, convenience-store picnic.']],note:'Dormire a Seomyeon = più vita e collegamenti. Dormire a Gwangan = più atmosfera serale.'},
    {n:6,place:'BUSAN',title:'Costa, quartieri e notte',desc:'Una Busan fisica: scogliere, scale, mare e mercati; meno “tour Instagram”, più giornatona fuori.',slots:[['Mattina','Huinnyeoul Culture Village presto, prima dei gruppi.'],['Pomeriggio','Igidae Coastal Walk oppure Taejongdae se volete meno trekking.'],['Sera','Nampo/Bupyeong Kkangtong Market → Seomyeon per bar o arcade.']],note:'Se non amate il pesce, Busan non è un problema: barbecue, dwaeji-gukbap, milmyeon, mandu e street food.'},
    {n:7,place:'BUSAN → CASA',title:'Ultima mattina senza ansia',desc:'Colazione, quartiere e rientro. Il volo decide se tornare in KTX o se serve una notte-buffer a Seoul/Incheon.',slots:[['Mattina','Caffè e passeggiata locale; niente attrazione “obbligatoria”.'],['Mezzogiorno','KTX verso Seoul se il volo è tardo / giorno successivo.'],['Partenza','Per volo mattutino: spostarsi a Seoul già la sera del giorno 6.']],note:'Non pianificare Busan → Seoul → ICN con coincidenze strette nello stesso giorno.'}
  ]},
  two:{label:'14 giorni',sub:'Seoul + Sokcho + Busan + Jeonju',stats:[['14 giorni','viaggio completo'],['4 basi','città · mare · montagna'],['₩3.9–5.8M','a terra, in due'],['1 giornata','Itaewon Class piena + sequel']],route:'Seoul 6 notti → Sokcho 2 → Busan 3 → Jeonju 2 → rientro. Più treni e bus, ma ogni blocco cambia davvero ambiente.',budget:{total:'€2.450–3.650',rows:[['13 notti','€1.050–1.550'],['Cibo + serate','€850–1.250'],['Trasporti','€280–400'],['Attività','€250–450']]},days:[
    {n:1,place:'SEOUL · YEONNAM',title:'Arrivo morbido',desc:'Hongdae/Yeonnam, cena, quartiere e sonno.',slots:[['Pomeriggio','AREX, check-in, eSIM/T-money.'],['Sera','Yeonnam e strade laterali.'],['Notte','Snack, birra o coin noraebang.']]},
    {n:2,place:'ITAewon class I',title:'Saeroyi walk',desc:'Baekbeom Plaza, Namsan e Noksapyeong fino alla notte.',slots:[['Mattina','Baekbeom Plaza + fortress wall.'],['Pomeriggio','Discesa verso Haebangchon, caffè, vicoli.'],['Sera','Noksapyeong Overpass → Seoul Bam/DanBam.']],note:'Il ponte rende al tramonto/notte: non bruciarlo a mezzogiorno.'},
    {n:3,place:'ITAewon class II',title:'Dietro le scene, poi Itaewon vera',desc:'Le location minori diventano un giorno di quartiere, non una caccia ai selfie.',slots:[['Mattina','G Guesthouse + Bogwang-dong.'],['Pomeriggio','Angel Wings, Children’s Park, Hannam side streets.'],['Notte','Itaewon/HBC: cena, bar piccolo, eventuale live/DJ.']],note:'G Guesthouse è un alloggio reale: rooftop e spazi interni solo se avete accesso come ospiti.'},
    {n:4,place:'SEOUL · JONGNO',title:'Palazzo → tavolino di plastica',desc:'Gyeongbokgung, Seochon, mercati, Ikseon e pojangmacha.',slots:[['Mattina','Gyeongbokgung presto.'],['Pomeriggio','Seochon + mercato + Ikseon.'],['Sera','Jongno 3-ga/Euljiro.']]},
    {n:5,place:'SEOUL · BUKHANSAN',title:'La montagna della metropoli',desc:'Hike vero, rientro in metro e jjimjilbang.',slots:[['Mattina','Bukhansan, scegliendo trail sul meteo.'],['Pomeriggio','Rientro + jjimjilbang.'],['Sera','Cena calda, serata corta.']]},
    {n:6,place:'SEOUL · QUOTIDIANA',title:'Mercato, Hangang, baseball',desc:'Una giornata costruita intorno a cose che fanno anche i residenti.',slots:[['Mattina','Mangwon Market e quartiere.'],['Pomeriggio','Hangang picnic/bici o Seongsu se piove.'],['Sera','KBO se in stagione; altrimenti noraebang + PC bang.']],note:'La partita di baseball è una delle serate migliori per stare dentro un pubblico locale senza dover “forzare” conversazioni.'},
    {n:7,place:'SEOUL → SOKCHO',title:'Dalla metro al Mare dell’Est',desc:'Bus per Sokcho e cambio netto di ritmo.',slots:[['Mattina','Bus Seoul → Sokcho.'],['Pomeriggio','Abai Village / porto / mercato centrale.'],['Sera','Sokcho Beach e cena semplice.']]},
    {n:8,place:'SEORAKSAN',title:'Giornata montagna',desc:'Ulsanbawi se siete in forma; alternativa Biryong/Towangseong più corta.',slots:[['Presto','Bus/taxi al parco, partenza prima delle folle.'],['Giorno','Trail scelto + pause vere.'],['Sera','Rientro Sokcho, bagno caldo e riposo.']],note:'Non trattare Ulsanbawi come passeggiata urbana: scarpe buone, acqua e meteo controllato.'},
    {n:9,place:'SOKCHO → BUSAN',title:'Il trasferimento lungo',desc:'Bus diretto verso Busan: 5–6 ore circa. È la giornata-cerniera del viaggio.',slots:[['Mattina','Partenza presto da Sokcho.'],['Pomeriggio','Arrivo e check-in.'],['Sera','Gwangalli al buio, cena e spiaggia.']],note:'Se odiate i trasferimenti lunghi, la sostituzione intelligente è Gyeongju al posto di Sokcho/Seoraksan.'},
    {n:10,place:'BUSAN · OVEST',title:'Scale, mare, mercato',desc:'Huinnyeoul e Nampo senza correre.',slots:[['Mattina','Huinnyeoul presto.'],['Pomeriggio','Taejongdae o Yongdusan/Nampo.'],['Sera','Bupyeong Kkangtong Market.']]},
    {n:11,place:'BUSAN · COSTA',title:'Camminare sopra il mare',desc:'Igidae Coastal Walk e Gwangalli come premio.',slots:[['Mattina','Igidae, tratto scelto in base alle gambe.'],['Pomeriggio','Caffè / riposo / spa.'],['Sera','Gwangalli, pub piccolo o picnic.']]},
    {n:12,place:'BUSAN → JEONJU',title:'Mattina locale, poi hanok',desc:'Un ultimo pezzo di Busan e trasferimento nel pomeriggio verso Jeonju.',slots:[['Mattina','Mercato/caffè di quartiere o baseball se l’orario coincide.'],['Pomeriggio','Treno/bus verso Jeonju.'],['Sera','Check-in hanok e prima passeggiata notturna.']]},
    {n:13,place:'JEONJU',title:'Hanok senza cosplay turistico',desc:'Centro storico, cortili, cibo e una sera di makgeolli.',slots:[['Mattina','Hanok Village + Gyeonggijeon presto.'],['Pomeriggio','Vicoli laterali, laboratorio o caffè, Gaengnidan-gil.'],['Sera','Makgeolli/traditional liquor dinner, tavolo lungo e piatti condivisi.']],note:'Dormire una notte in hanok cambia più l’esperienza che aggiungere un altro museo.'},
    {n:14,place:'JEONJU → SEOUL/ICN',title:'Rientro con margine',desc:'KTX da Jeonju verso Seoul/Yongsan e aeroporto solo con margine abbondante.',slots:[['Mattina','Colazione e ultimo giro.'],['Trasferimento','KTX Jeonju → area Seoul ~1h40.'],['Volo','Se è presto: anticipare il rientro alla sera del giorno 13.']],note:'Il piano migliore dipende dall’orario del volo: la notte-buffer vicino a Seoul/ICN vale più di una corsa stressante.'}
  ]}
};
