(() => {
'use strict';
const $ = id => document.getElementById(id);
const STORAGE_PREFS='content-review-prefs-v4';
const STORAGE_DRAFT='content-review-draft-v4';
const DEFAULTS={language:'it',theme:'dark',vision:'normal',accent:'classic',largeText:false,highContrast:false,reducedMotion:false,sounds:false,haptics:false,saveAnswers:true,rememberStep:true,showProgress:true,showHints:true,showLegends:true,institutionalHumor:true,compact:false,readingMode:false,confirmShare:false,includeDate:true,detailedReport:true,showStatistics:true,anonymous:false,allowSkip:false,keyboard:false};
const Q={
it:['Quanto ti ha interessato?','Quanto ti ha intrattenuto?','Quanto volevi arrivare alla fine?','Qualità del montaggio','Qualità dell’audio','Chiarezza del contenuto','Originalità dell’idea','Ritmo generale','Quanto ti ha sorpreso?','Quanto era divertente?','Quanto ti è rimasto in testa?','Lo riguarderesti volentieri?','Lo consiglieresti a qualcuno?','È valso il tempo impiegato?','Voto complessivo, senza pressioni.'],
en:['How interesting was it?','How entertaining was it?','How much did you want to finish it?','Editing quality','Audio quality','Content clarity','Originality of the idea','Overall pacing','How surprising was it?','How funny was it?','How memorable was it?','Would you watch it again?','Would you recommend it?','Was it worth your time?','Overall rating, no pressure.'],
es:['¿Cuánto te interesó?','¿Cuánto te entretuvo?','¿Cuánto querías verlo hasta el final?','Calidad del montaje','Calidad del audio','Claridad del contenido','Originalidad de la idea','Ritmo general','¿Cuánto te sorprendió?','¿Cuánto te hizo reír?','¿Cuánto lo recordarás?','¿Lo volverías a ver?','¿Lo recomendarías?','¿Valió la pena tu tiempo?','Nota general, sin presiones.'],
zh:['你觉得有多有趣？','它有多吸引你？','你有多想看完？','剪辑质量','音频质量','内容清晰度','创意原创性','整体节奏','它有多让你惊喜？','它有多好笑？','你有多难忘？','你愿意再看一遍吗？','你愿意推荐吗？','值得花时间吗？','总体评分，不施加压力。'],
fr:['À quel point était-ce intéressant ?','À quel point était-ce divertissant ?','Avais-tu envie de voir la fin ?','Qualité du montage','Qualité du son','Clarté du contenu','Originalité de l’idée','Rythme général','Était-ce surprenant ?','Était-ce drôle ?','Était-ce mémorable ?','Le regarderais-tu encore ?','Le recommanderais-tu ?','Cela valait-il ton temps ?','Note globale, sans pression.'],
de:['Wie interessant war es?','Wie unterhaltsam war es?','Wie sehr wolltest du es zu Ende sehen?','Schnittqualität','Audioqualität','Verständlichkeit','Originalität der Idee','Allgemeines Tempo','Wie überraschend war es?','Wie lustig war es?','Wie einprägsam war es?','Würdest du es erneut ansehen?','Würdest du es empfehlen?','War es deine Zeit wert?','Gesamtbewertung, ganz ohne Druck.'],
pt:['Quanto te interessou?','Quanto te entreteve?','Quanto quiseste ver até ao fim?','Qualidade da edição','Qualidade do áudio','Clareza do conteúdo','Originalidade da ideia','Ritmo geral','Quanto te surpreendeu?','Quanto te fez rir?','Quanto ficou na memória?','Voltarias a ver?','Recomendarias a alguém?','Valeu o teu tempo?','Nota geral, sem pressão.'],
ja:['どれくらい興味を持った？','どれくらい楽しめた？','最後まで見たいと思った？','編集の質','音声の質','内容の分かりやすさ','アイデアの独創性','全体のテンポ','どれくらい驚いた？','どれくらい面白かった？','印象に残った？','もう一度見たい？','人にすすめたい？','時間を使う価値はあった？','総合評価。圧力はありません。']
};
const T={
it:{
skip:'Vai alla valutazione',settingsShort:'Opzioni',heroEyebrow:'DIPARTIMENTO DI OPINIONI NON RICHIESTE · EST. 2026',heroLine1:'NE VALEVA',heroLine2:'LA PENA?',heroLine3:'DAVVERO.',heroDesc:'Hai ricevuto un contenuto. È arrivato il momento di valutarlo con un rigore completamente ingiustificato. Ci vogliono circa due minuti.',start:'Inizia la valutazione',surveyEyebrow:'IL QUESTIONARIO / EDIZIONE SPECIALE',surveyTitle:'METTI A VERBALE.',surveyAside:'Nessun account. Nessun voto pubblico. Nessun motivo concreto per tutta questa procedura.',settingsEyebrow:'AREA RISERVATA A CHI INSISTE',settingsTitle:'IMPOSTAZIONI.',savedLocally:'Preferenze salvate solo su questo dispositivo.',done:'Fatto ✓',back:'Indietro',next:'Continua',strip1:'GIUDIZIO / PERCEZIONE',strip2:'DICHIARAZIONI / VERDETTO',strip3:'SERISSIMO (NON VERIFICATO)',footerText:'Nessuna autorità competente è stata consultata.',backHome:'← Torna a SwadyaSpace',
stageTitles:['PRIMA IMPRESSIONE.','SOTTO LA LENTE.','UN PO’ PIÙ A FONDO.','TRACCE NEL CERVELLO.','LA SENTENZA.','CONTROLLO QUALITÀ.','ULTIMA FORMALITÀ.','IL VERDETTO.'],
stageDescriptions:['Partiamo dalle cose essenziali. Tre voti, nessuna complicazione.','Analisi tecnica. Siamo sorprendentemente seri a riguardo.','Originalità e ritmo. La commissione sta prendendo appunti.','Considerazioni a medio termine. O almeno nei prossimi sette minuti.','Tre domande decisive. Rispondi senza guardare il soffitto.','Le seguenti dichiarazioni verranno prese sul serio senza una ragione precisa.','Identificarti è facoltativo. Il contenuto è già stato giudicato.','La commissione ha deliberato. Non è chiaro chi l’abbia nominata.'],
phase:'SEZIONE',answers:'RISPOSTE',protocol:'PROTOCOLLO ATTIVO',low:'Per niente',high:'Moltissimo',questionHint:'Un solo numero. Il dipartimento non accetta mezzi punti.',missing:'Dai un voto a tutte e tre le domande per continuare.',missingOverall:'Serve almeno una valutazione.',reportBtn:'Genera il verdetto',restart:'Nuova valutazione',seen:'Hai effettivamente visto tutto il contenuto?',confirmSeen:'Confermi la dichiarazione precedente?',emotion:'Sensazione predominante',selectAnswer:'Seleziona una risposta',seenOptions:['Sì, dall’inizio alla fine','Quasi tutto','No, ma ho comunque un’opinione','Non posso confermare'],confirmOptions:['Confermo','Confermo, ma non sotto giuramento','Preferisco non rispondere'],emotionOptions:['Divertimento','Curiosità','Confusione','Indifferenza','Disagio contenuto','Apprezzamento involontario'],
name:'Firma del valutatore (facoltativa)',namePlaceholder:'Come vuoi farti chiamare',notes:'Osservazioni finali (facoltative)',notesPlaceholder:'Una frase, una critica, un’analisi sproporzionata…',noIdentity:'Nessun dato personale è richiesto. Puoi lasciare tutto vuoto.',optionalConfirm:'Confermo di aver risposto con ragionevole sincerità.',noPledge:'La firma non è necessaria. Nemmeno una promessa.',
reportEyebrow:'DOCUMENTO GENERATO / USO PRIVATO',reportReady:'VALUTAZIONE COMPLETATA',scoreLabel:'PUNTEGGIO MEDIO',reportSummary:'Sintesi della commissione',ratingCount:'Valutazioni registrate',reportCategory:['Coinvolgimento','Qualità tecnica','Idea e ritmo','Impatto','Giudizio finale'],verdicts:['La commissione non raccomanda un secondo esame.','Sono emerse alcune riserve. Nessuno è stato informato.','Esito accettabile. Il documento può essere archiviato.','Un contenuto più che rispettabile. Procedura conclusa.','Approvazione piena. Il dipartimento è moderatamente impressionato.'],whatsapp:'Condividi su WhatsApp ↗',copy:'Copia rapporto',nativeShare:'Altre app',download:'Scarica JSON',print:'Stampa',preview:'ANTEPRIMA / REPORT',noRating:'N/D',anonymousName:'Non dichiarato',reportFooter:'Questo documento non ha validità legale né motivo di esistere.',reportTitle:'CONTENT REVIEW — RAPPORTO',evaluation:'Valutazione',finalScore:'Media',watchedReport:'Visione completa',confirmationReport:'Conferma',emotionReport:'Sensazione',commentReport:'Commento',nameReport:'Valutatore',notProvided:'Non indicato',shareConfirm:'Vuoi aprire WhatsApp con il rapporto pronto?',copied:'Rapporto copiato.',failedCopy:'Impossibile copiare: usa la condivisione.',settingsReset:'Ripristina opzioni',clearAnswers:'Cancella risposte',resetConfirm:'Cancellare tutte le risposte salvate su questo dispositivo?',resetDone:'Risposte cancellate.',optionsReset:'Impostazioni ripristinate.',continueFirst:'Completa la sezione prima di procedere.',shareError:'Condivisione non disponibile su questo browser.',saved:'Salvato in locale',instructions:'Le opzioni sono indipendenti e completamente facoltative.',keyboardHint:'Scorciatoia: tasti 1–5 per votare.',
groups:['Lingua e aspetto','Accessibilità','Interazioni','Questionario e privacy','Report e condivisione'],settings:{
language:'Lingua dell’interfaccia',theme:'Tema',vision:'Modalità daltonismo',accent:'Colore accento',largeText:'Testo più grande',highContrast:'Contrasto elevato',reducedMotion:'Riduci le animazioni',sounds:'Suoni dei pulsanti',haptics:'Vibrazione al voto',saveAnswers:'Salva le risposte in locale',rememberStep:'Ricorda l’ultima sezione',showProgress:'Barra di avanzamento',showHints:'Suggerimenti alle domande',showLegends:'Estremi della scala 1–5',institutionalHumor:'Commenti istituzionali',compact:'Layout compatto',readingMode:'Modalità lettura',confirmShare:'Conferma prima di condividere',includeDate:'Data nel rapporto',detailedReport:'Elenco completo dei voti',showStatistics:'Grafico riepilogativo',anonymous:'Anonimato nel rapporto',allowSkip:'Permetti domande senza voto',keyboard:'Scorciatoie da tastiera'},choices:{dark:'Scuro',light:'Chiaro',system:'Sistema',normal:'Standard',deuter:'Deuteranopia',protan:'Protanopia',tritan:'Tritanopia',classic:'Lime',cobalt:'Blu',peach:'Pesca'}},
en:{
skip:'Skip to review',settingsShort:'Options',heroEyebrow:'DEPARTMENT OF UNSOLICITED OPINIONS · EST. 2026',heroLine1:'WAS IT',heroLine2:'REALLY',heroLine3:'WORTH IT?',heroDesc:'You received a piece of content. Now it is time to assess it with completely unjustified rigor. About two minutes.',start:'Start the review',surveyEyebrow:'THE QUESTIONNAIRE / SPECIAL EDITION',surveyTitle:'ON THE RECORD.',surveyAside:'No account. No public rating. No compelling reason for any of this.',settingsEyebrow:'ONLY FOR PEOPLE WHO INSIST',settingsTitle:'SETTINGS.',savedLocally:'Preferences are stored only on this device.',done:'Done ✓',back:'Back',next:'Continue',strip1:'JUDGMENT / PERCEPTION',strip2:'STATEMENTS / VERDICT',strip3:'VERY SERIOUS (UNVERIFIED)',footerText:'No competent authority was consulted.',backHome:'← Back to SwadyaSpace',
stageTitles:['FIRST IMPRESSION.','UNDER THE LENS.','LOOKING DEEPER.','TRACES IN THE BRAIN.','THE SENTENCE.','QUALITY CONTROL.','ONE LAST FORMALITY.','THE VERDICT.'],
stageDescriptions:['The essentials. Three ratings, no complications.','Technical analysis. We take this surprisingly seriously.','Originality and pace. The committee is taking notes.','Medium-term considerations. Or at least the next seven minutes.','Three decisive questions. Answer without staring at the ceiling.','These declarations will be treated seriously for no particular reason.','Your name is optional. The content has already been judged.','The committee has decided. Nobody remembers appointing it.'],
phase:'SECTION',answers:'ANSWERS',protocol:'ACTIVE PROTOCOL',low:'Not at all',high:'Very much',questionHint:'One number. The department does not accept half points.',missing:'Rate all three questions to continue.',missingOverall:'At least one rating is required.',reportBtn:'Generate verdict',restart:'New review',seen:'Did you actually watch the whole content?',confirmSeen:'Do you confirm the previous statement?',emotion:'Dominant feeling',selectAnswer:'Select an answer',seenOptions:['Yes, beginning to end','Almost all of it','No, but I still have an opinion','Cannot confirm'],confirmOptions:['Confirmed','Confirmed, but not under oath','Prefer not to answer'],emotionOptions:['Amusement','Curiosity','Confusion','Indifference','Mild discomfort','Unintentional appreciation'],
name:'Reviewer signature (optional)',namePlaceholder:'What should we call you?',notes:'Final remarks (optional)',notesPlaceholder:'One sentence, one criticism, one unreasonable analysis…',noIdentity:'No personal information is needed. You may leave everything empty.',optionalConfirm:'I declare my answers reasonably sincere.',noPledge:'A signature is unnecessary. So is a promise.',
reportEyebrow:'DOCUMENT GENERATED / PRIVATE USE',reportReady:'REVIEW COMPLETE',scoreLabel:'AVERAGE SCORE',reportSummary:'Committee summary',ratingCount:'Ratings recorded',reportCategory:['Engagement','Technical quality','Idea and pacing','Impact','Final judgment'],verdicts:['The committee does not recommend a second viewing.','Some concerns have emerged. Nobody was notified.','Acceptable result. This file may be archived.','A more than respectable piece of content. Case closed.','Full approval. The department is moderately impressed.'],whatsapp:'Share on WhatsApp ↗',copy:'Copy report',nativeShare:'Other apps',download:'Download JSON',print:'Print',preview:'PREVIEW / REPORT',noRating:'N/A',anonymousName:'Not disclosed',reportFooter:'This document has neither legal standing nor any good reason to exist.',reportTitle:'CONTENT REVIEW — REPORT',evaluation:'Rating',finalScore:'Average',watchedReport:'Watched in full',confirmationReport:'Confirmation',emotionReport:'Feeling',commentReport:'Comment',nameReport:'Reviewer',notProvided:'Not specified',shareConfirm:'Open WhatsApp with your report?',copied:'Report copied.',failedCopy:'Copy unavailable. Try sharing.',settingsReset:'Reset options',clearAnswers:'Clear answers',resetConfirm:'Delete all answers saved on this device?',resetDone:'Answers deleted.',optionsReset:'Options restored.',continueFirst:'Finish this section to continue.',shareError:'Sharing is not supported here.',saved:'Saved locally',instructions:'Every option is independent and completely optional.',keyboardHint:'Shortcut: press 1–5 to rate.',
groups:['Language & appearance','Accessibility','Interactions','Questionnaire & privacy','Report & sharing'],settings:{language:'Interface language',theme:'Theme',vision:'Color vision mode',accent:'Accent color',largeText:'Larger text',highContrast:'High contrast',reducedMotion:'Reduce motion',sounds:'Button sounds',haptics:'Vibration on rating',saveAnswers:'Save answers locally',rememberStep:'Remember last section',showProgress:'Progress bar',showHints:'Question hints',showLegends:'1–5 scale labels',institutionalHumor:'Institutional remarks',compact:'Compact layout',readingMode:'Reading mode',confirmShare:'Confirm before sharing',includeDate:'Date in report',detailedReport:'Full list of ratings',showStatistics:'Summary chart',anonymous:'Anonymous report',allowSkip:'Allow unrated questions',keyboard:'Keyboard shortcuts'},choices:{dark:'Dark',light:'Light',system:'System',normal:'Standard',deuter:'Deuteranopia',protan:'Protanopia',tritan:'Tritanopia',classic:'Lime',cobalt:'Blue',peach:'Peach'}},
es:{
skip:'Ir al cuestionario',settingsShort:'Opciones',heroEyebrow:'DEPARTAMENTO DE OPINIONES NO SOLICITADAS · DESDE 2026',heroLine1:'¿VALIÓ',heroLine2:'LA PENA',heroLine3:'DE VERDAD?',heroDesc:'Has recibido un contenido. Es hora de evaluarlo con un rigor totalmente injustificado. Unos dos minutos.',start:'Empezar evaluación',surveyEyebrow:'EL CUESTIONARIO / EDICIÓN ESPECIAL',surveyTitle:'QUE CONSTE.',surveyAside:'Sin cuenta. Sin votos públicos. Sin ninguna razón para este trámite.',settingsEyebrow:'SOLO PARA QUIENES INSISTEN',settingsTitle:'AJUSTES.',savedLocally:'Las preferencias se guardan solo en este dispositivo.',done:'Listo ✓',back:'Atrás',next:'Continuar',strip1:'JUICIO / PERCEPCIÓN',strip2:'DECLARACIONES / VEREDICTO',strip3:'MUY SERIO (SIN VERIFICAR)',footerText:'No se consultó a ninguna autoridad competente.',backHome:'← Volver a SwadyaSpace',
stageTitles:['PRIMERA IMPRESIÓN.','BAJO LA LUPA.','MÁS A FONDO.','HUELLAS EN LA MENTE.','LA SENTENCIA.','CONTROL DE CALIDAD.','ÚLTIMO TRÁMITE.','EL VEREDICTO.'],
stageDescriptions:['Lo esencial. Tres notas, sin complicaciones.','Análisis técnico. Lo tomamos sorprendentemente en serio.','Originalidad y ritmo. El comité toma notas.','Consideraciones a medio plazo. O siete minutos como mucho.','Tres preguntas decisivas. Responde sin mirar al techo.','Estas declaraciones se tomarán en serio sin motivo concreto.','El nombre es opcional. El contenido ya ha sido juzgado.','El comité ha decidido. Nadie sabe quién lo nombró.'],
phase:'SECCIÓN',answers:'RESPUESTAS',protocol:'PROTOCOLO ACTIVO',low:'Nada',high:'Muchísimo',questionHint:'Un número. El departamento no acepta medias notas.',missing:'Puntúa las tres preguntas para continuar.',missingOverall:'Hace falta al menos una nota.',reportBtn:'Generar veredicto',restart:'Nueva evaluación',seen:'¿Viste de verdad todo el contenido?',confirmSeen:'¿Confirmas la declaración anterior?',emotion:'Sensación principal',selectAnswer:'Elige una respuesta',seenOptions:['Sí, de principio a fin','Casi todo','No, pero tengo una opinión','No puedo confirmarlo'],confirmOptions:['Confirmo','Confirmo, pero no bajo juramento','Prefiero no responder'],emotionOptions:['Diversión','Curiosidad','Confusión','Indiferencia','Incomodidad leve','Aprecio involuntario'],
name:'Firma del evaluador (opcional)',namePlaceholder:'¿Cómo quieres llamarte?',notes:'Observaciones finales (opcionales)',notesPlaceholder:'Una frase, una crítica, un análisis desproporcionado…',noIdentity:'No se necesitan datos personales. Puedes dejarlo todo vacío.',optionalConfirm:'Declaro que mis respuestas son razonablemente sinceras.',noPledge:'No hace falta firmar. Tampoco prometer.',
reportEyebrow:'DOCUMENTO GENERADO / USO PRIVADO',reportReady:'EVALUACIÓN COMPLETADA',scoreLabel:'NOTA MEDIA',reportSummary:'Resumen del comité',ratingCount:'Notas registradas',reportCategory:['Interés','Calidad técnica','Idea y ritmo','Impacto','Juicio final'],verdicts:['El comité no recomienda verlo una segunda vez.','Han surgido algunas reservas. No se notificó a nadie.','Resultado aceptable. Se puede archivar.','Contenido bastante respetable. Caso cerrado.','Aprobación plena. El departamento está moderadamente impresionado.'],whatsapp:'Compartir en WhatsApp ↗',copy:'Copiar informe',nativeShare:'Otras apps',download:'Descargar JSON',print:'Imprimir',preview:'VISTA PREVIA / INFORME',noRating:'N/D',anonymousName:'Sin declarar',reportFooter:'Este documento no tiene validez legal ni motivo para existir.',reportTitle:'CONTENT REVIEW — INFORME',evaluation:'Nota',finalScore:'Media',watchedReport:'Visto completo',confirmationReport:'Confirmación',emotionReport:'Sensación',commentReport:'Comentario',nameReport:'Evaluador',notProvided:'No indicado',shareConfirm:'¿Abrir WhatsApp con el informe?',copied:'Informe copiado.',failedCopy:'No se pudo copiar. Prueba compartir.',settingsReset:'Restablecer opciones',clearAnswers:'Borrar respuestas',resetConfirm:'¿Borrar todas las respuestas de este dispositivo?',resetDone:'Respuestas borradas.',optionsReset:'Opciones restauradas.',continueFirst:'Completa esta sección antes de seguir.',shareError:'No se puede compartir aquí.',saved:'Guardado localmente',instructions:'Todas las opciones son independientes y opcionales.',keyboardHint:'Atajo: teclas 1–5 para puntuar.',
groups:['Idioma y aspecto','Accesibilidad','Interacciones','Cuestionario y privacidad','Informe y compartir'],settings:{language:'Idioma',theme:'Tema',vision:'Modo daltonismo',accent:'Color de acento',largeText:'Texto más grande',highContrast:'Alto contraste',reducedMotion:'Reducir animaciones',sounds:'Sonidos de botones',haptics:'Vibración al puntuar',saveAnswers:'Guardar respuestas localmente',rememberStep:'Recordar última sección',showProgress:'Barra de progreso',showHints:'Ayudas en preguntas',showLegends:'Extremos de escala 1–5',institutionalHumor:'Comentarios institucionales',compact:'Diseño compacto',readingMode:'Modo lectura',confirmShare:'Confirmar antes de compartir',includeDate:'Fecha en informe',detailedReport:'Lista completa de notas',showStatistics:'Gráfico resumen',anonymous:'Informe anónimo',allowSkip:'Permitir preguntas sin nota',keyboard:'Atajos de teclado'},choices:{dark:'Oscuro',light:'Claro',system:'Sistema',normal:'Estándar',deuter:'Deuteranopía',protan:'Protanopía',tritan:'Tritanopía',classic:'Lima',cobalt:'Azul',peach:'Melocotón'}},
zh:{
skip:'跳转到评价',settingsShort:'设置',heroEyebrow:'非邀约意见部门 · 成立于 2026 年',heroLine1:'这个内容',heroLine2:'真的',heroLine3:'值得吗？',heroDesc:'你收到了一条内容。现在是时候以完全没有必要的严谨态度评价它了。大约需要两分钟。',start:'开始评价',surveyEyebrow:'特别评估问卷',surveyTitle:'正式记录。',surveyAside:'无需账户。评分不公开。也没有必要如此认真。',settingsEyebrow:'只供特别坚持的人士使用',settingsTitle:'设置。',savedLocally:'设置仅保存在本设备。',done:'完成 ✓',back:'返回',next:'继续',strip1:'判断 / 感受',strip2:'声明 / 结论',strip3:'非常严肃（未经证实）',footerText:'本机构未咨询任何主管部门。',backHome:'← 返回 SwadyaSpace',
stageTitles:['第一印象。','技术检查。','深入分析。','留在脑海里。','最后裁决。','质量核查。','最后一项手续。','最终结论。'],
stageDescriptions:['从最重要的开始。三个评分，没有复杂步骤。','技术分析。我们出奇地认真。','创意与节奏。委员会正在做笔记。','中期印象。至少是接下来的七分钟。','三个决定性问题。请不要抬头思考太久。','这些声明会被无缘无故地认真对待。','署名完全自愿。内容已经被评判。','委员会已经决定。没人记得是谁任命的。'],
phase:'部分',answers:'评分',protocol:'流程进行中',low:'完全没有',high:'非常',questionHint:'请选整数。不接受半分。',missing:'请完成本部分的三个评分。',missingOverall:'至少需要一个评分。',reportBtn:'生成结论',restart:'重新评价',seen:'你真的看完了整个内容吗？',confirmSeen:'确认刚才的声明吗？',emotion:'主要感受',selectAnswer:'请选择',seenOptions:['是的，从头到尾','看了大部分','没有，但我仍有意见','无法确认'],confirmOptions:['确认','确认，但不是宣誓','不愿回答'],emotionOptions:['开心','好奇','困惑','无所谓','轻微不适','意外欣赏'],
name:'评价者署名（可选）',namePlaceholder:'希望如何称呼你？',notes:'补充意见（可选）',notesPlaceholder:'一句话、一点批评，或过分认真的分析……',noIdentity:'无需提供任何个人信息。可以全部留空。',optionalConfirm:'我声明答案大致真实。',noPledge:'签名没有必要。承诺也没有必要。',
reportEyebrow:'报告已生成 / 私人用途',reportReady:'评价已完成',scoreLabel:'平均分',reportSummary:'委员会摘要',ratingCount:'已记录评分',reportCategory:['参与感','技术质量','创意与节奏','影响力','最终评价'],verdicts:['委员会不建议再看一次。','存在一些疑虑。没有人收到通知。','结果尚可。可以存档。','内容相当不错。结案。','完全通过。部门略感惊讶。'],whatsapp:'通过 WhatsApp 分享 ↗',copy:'复制报告',nativeShare:'其他应用',download:'下载 JSON',print:'打印',preview:'报告预览',noRating:'无',anonymousName:'未公开',reportFooter:'本文件不具有法律效力，也没什么存在的必要。',reportTitle:'CONTENT REVIEW — 评价报告',evaluation:'评分',finalScore:'平均',watchedReport:'完整观看',confirmationReport:'确认',emotionReport:'感受',commentReport:'评论',nameReport:'评价者',notProvided:'未填写',shareConfirm:'使用 WhatsApp 打开报告？',copied:'报告已复制。',failedCopy:'复制失败，请尝试分享。',settingsReset:'重置设置',clearAnswers:'清空答案',resetConfirm:'删除本设备的所有答案？',resetDone:'答案已清空。',optionsReset:'设置已重置。',continueFirst:'请先完成本部分。',shareError:'此浏览器无法分享。',saved:'已保存到本地',instructions:'每项设置都独立且可选。',keyboardHint:'快捷键：1–5 评分。',
groups:['语言和外观','辅助功能','交互','问卷与隐私','报告与分享'],settings:{language:'界面语言',theme:'主题',vision:'色觉模式',accent:'强调色',largeText:'放大文字',highContrast:'高对比度',reducedMotion:'减少动画',sounds:'按钮音效',haptics:'评分时振动',saveAnswers:'本地保存答案',rememberStep:'记住当前进度',showProgress:'进度条',showHints:'问题提示',showLegends:'1–5 分说明',institutionalHumor:'机构式幽默',compact:'紧凑布局',readingMode:'阅读模式',confirmShare:'分享前确认',includeDate:'报告中包含日期',detailedReport:'完整评分列表',showStatistics:'汇总图表',anonymous:'匿名报告',allowSkip:'允许跳过评分',keyboard:'键盘快捷键'},choices:{dark:'深色',light:'浅色',system:'跟随系统',normal:'标准',deuter:'绿色色觉异常',protan:'红色色觉异常',tritan:'蓝色色觉异常',classic:'青柠',cobalt:'蓝色',peach:'桃色'}},
fr:{
skip:'Aller au questionnaire',settingsShort:'Options',heroEyebrow:'DÉPARTEMENT DES AVIS NON SOLLICITÉS · DEPUIS 2026',heroLine1:'ÇA VALAIT',heroLine2:'VRAIMENT',heroLine3:'LE COUP ?',heroDesc:'Tu as reçu un contenu. Il est temps de l’évaluer avec une rigueur totalement injustifiée. Deux minutes environ.',start:'Commencer',surveyEyebrow:'QUESTIONNAIRE / ÉDITION SPÉCIALE',surveyTitle:'AU PROCÈS-VERBAL.',surveyAside:'Sans compte. Sans note publique. Sans raison valable pour cette procédure.',settingsEyebrow:'RÉSERVÉ AUX PERSONNES INSISTANTES',settingsTitle:'PARAMÈTRES.',savedLocally:'Préférences enregistrées uniquement sur cet appareil.',done:'Terminé ✓',back:'Retour',next:'Continuer',strip1:'JUGEMENT / PERCEPTION',strip2:'DÉCLARATIONS / VERDICT',strip3:'TRÈS SÉRIEUX (NON VÉRIFIÉ)',footerText:'Aucune autorité compétente n’a été consultée.',backHome:'← Retour à SwadyaSpace',
stageTitles:['PREMIÈRE IMPRESSION.','À LA LOUPE.','UN PEU PLUS LOIN.','DANS LA MÉMOIRE.','LE JUGEMENT.','CONTRÔLE QUALITÉ.','DERNIÈRE FORMALITÉ.','LE VERDICT.'],
stageDescriptions:['L’essentiel. Trois notes, sans complication.','Analyse technique. Nous prenons cela étonnamment au sérieux.','Originalité et rythme. Le comité prend des notes.','Considérations à moyen terme. Ou sept minutes.','Trois questions décisives. Réponds sans fixer le plafond.','Ces déclarations seront prises au sérieux sans raison précise.','Ton nom est facultatif. Le contenu est déjà jugé.','Le comité a statué. Personne ne sait qui l’a nommé.'],
phase:'SECTION',answers:'RÉPONSES',protocol:'PROTOCOLE ACTIF',low:'Pas du tout',high:'Énormément',questionHint:'Un seul chiffre. Les demi-points ne sont pas admis.',missing:'Note les trois questions pour continuer.',missingOverall:'Il faut au moins une note.',reportBtn:'Générer le verdict',restart:'Nouvel avis',seen:'As-tu vraiment tout regardé ?',confirmSeen:'Confirmes-tu ta déclaration ?',emotion:'Sentiment dominant',selectAnswer:'Choisir une réponse',seenOptions:['Oui, du début à la fin','Presque tout','Non, mais j’ai un avis','Impossible de confirmer'],confirmOptions:['Je confirme','Je confirme, mais pas sous serment','Je préfère ne pas répondre'],emotionOptions:['Amusement','Curiosité','Confusion','Indifférence','Léger malaise','Appréciation involontaire'],
name:'Signature (facultative)',namePlaceholder:'Comment doit-on t’appeler ?',notes:'Observations finales (facultatives)',notesPlaceholder:'Une phrase, une critique, une analyse disproportionnée…',noIdentity:'Aucune donnée personnelle exigée. Tu peux tout laisser vide.',optionalConfirm:'Je déclare être raisonnablement sincère.',noPledge:'Pas besoin de signer. Ni de promettre.',
reportEyebrow:'DOCUMENT GÉNÉRÉ / USAGE PRIVÉ',reportReady:'ÉVALUATION TERMINÉE',scoreLabel:'NOTE MOYENNE',reportSummary:'Résumé du comité',ratingCount:'Notes enregistrées',reportCategory:['Intérêt','Qualité technique','Idée et rythme','Impact','Jugement final'],verdicts:['Le comité déconseille un second visionnage.','Quelques réserves ont été émises. Personne n’a été informé.','Résultat acceptable. Classement possible.','Un contenu plus que respectable. Affaire classée.','Approbation totale. Le département est modérément impressionné.'],whatsapp:'Partager sur WhatsApp ↗',copy:'Copier le rapport',nativeShare:'Autres applis',download:'Télécharger JSON',print:'Imprimer',preview:'APERÇU / RAPPORT',noRating:'N/D',anonymousName:'Non déclaré',reportFooter:'Ce document n’a aucune valeur juridique ni raison d’exister.',reportTitle:'CONTENT REVIEW — RAPPORT',evaluation:'Note',finalScore:'Moyenne',watchedReport:'Visionnage complet',confirmationReport:'Confirmation',emotionReport:'Sentiment',commentReport:'Commentaire',nameReport:'Évaluateur',notProvided:'Non indiqué',shareConfirm:'Ouvrir WhatsApp avec le rapport ?',copied:'Rapport copié.',failedCopy:'Copie impossible. Essaie le partage.',settingsReset:'Réinitialiser options',clearAnswers:'Effacer réponses',resetConfirm:'Effacer les réponses sur cet appareil ?',resetDone:'Réponses effacées.',optionsReset:'Options réinitialisées.',continueFirst:'Termine cette section.',shareError:'Partage indisponible.',saved:'Enregistré localement',instructions:'Toutes les options sont indépendantes et facultatives.',keyboardHint:'Raccourci : touches 1 à 5.',
groups:['Langue et apparence','Accessibilité','Interactions','Questionnaire et vie privée','Rapport et partage'],settings:{language:'Langue',theme:'Thème',vision:'Mode daltonisme',accent:'Couleur accent',largeText:'Texte agrandi',highContrast:'Contraste élevé',reducedMotion:'Réduire les animations',sounds:'Sons des boutons',haptics:'Vibration à la note',saveAnswers:'Sauvegarder les réponses',rememberStep:'Reprendre à la dernière section',showProgress:'Barre de progression',showHints:'Conseils pour les questions',showLegends:'Légendes de 1 à 5',institutionalHumor:'Commentaires institutionnels',compact:'Affichage compact',readingMode:'Mode lecture',confirmShare:'Confirmer avant partage',includeDate:'Date dans le rapport',detailedReport:'Liste complète des notes',showStatistics:'Graphique récapitulatif',anonymous:'Rapport anonyme',allowSkip:'Permettre de ne pas noter',keyboard:'Raccourcis clavier'},choices:{dark:'Sombre',light:'Clair',system:'Système',normal:'Standard',deuter:'Deutéranopie',protan:'Protanopie',tritan:'Tritanopie',classic:'Citron vert',cobalt:'Bleu',peach:'Pêche'}},
de:{
skip:'Zur Bewertung',settingsShort:'Optionen',heroEyebrow:'ABTEILUNG FÜR UNGEFRAGTE MEINUNGEN · SEIT 2026',heroLine1:'WAR ES',heroLine2:'WIRKLICH',heroLine3:'WERT?',heroDesc:'Du hast einen Inhalt erhalten. Zeit für eine völlig unverhältnismäßige Bewertung. Etwa zwei Minuten.',start:'Bewertung starten',surveyEyebrow:'FRAGEBOGEN / SONDERAUSGABE',surveyTitle:'ZU PROTOKOLL.',surveyAside:'Kein Konto. Keine öffentliche Bewertung. Kein guter Grund für dieses Verfahren.',settingsEyebrow:'NUR FÜR BESONDERS HARTNÄCKIGE',settingsTitle:'EINSTELLUNGEN.',savedLocally:'Einstellungen werden nur auf diesem Gerät gespeichert.',done:'Fertig ✓',back:'Zurück',next:'Weiter',strip1:'URTEIL / WAHRNEHMUNG',strip2:'ERKLÄRUNGEN / URTEIL',strip3:'SEHR ERNST (UNGEPRÜFT)',footerText:'Keine zuständige Behörde wurde konsultiert.',backHome:'← Zu SwadyaSpace',
stageTitles:['ERSTER EINDRUCK.','UNTER DER LUPE.','GENAUER HINSEHEN.','IM GEDÄCHTNIS.','DAS URTEIL.','QUALITÄTSKONTROLLE.','LETZTE FORMALITÄT.','DAS ERGEBNIS.'],
stageDescriptions:['Das Wichtigste. Drei Bewertungen, keine Komplikationen.','Technische Analyse. Wir nehmen das überraschend ernst.','Originalität und Tempo. Der Ausschuss macht Notizen.','Mittelfristige Eindrücke. Oder sieben Minuten.','Drei entscheidende Fragen. Nicht an die Decke starren.','Diese Aussagen werden grundlos sehr ernst genommen.','Dein Name ist freiwillig. Der Inhalt ist bereits bewertet.','Der Ausschuss hat entschieden. Niemand hat ihn gewählt.'],
phase:'ABSCHNITT',answers:'ANTWORTEN',protocol:'AKTIVES PROTOKOLL',low:'Gar nicht',high:'Sehr',questionHint:'Eine Zahl. Halbe Punkte gelten nicht.',missing:'Bitte alle drei Fragen bewerten.',missingOverall:'Mindestens eine Bewertung nötig.',reportBtn:'Ergebnis erstellen',restart:'Neue Bewertung',seen:'Hast du wirklich alles angesehen?',confirmSeen:'Bestätigst du die vorige Aussage?',emotion:'Vorherrschendes Gefühl',selectAnswer:'Antwort wählen',seenOptions:['Ja, von Anfang bis Ende','Fast alles','Nein, aber ich habe trotzdem eine Meinung','Kann ich nicht bestätigen'],confirmOptions:['Bestätigt','Bestätigt, aber nicht unter Eid','Lieber nicht antworten'],emotionOptions:['Freude','Neugier','Verwirrung','Gleichgültigkeit','Leichtes Unbehagen','Unfreiwillige Anerkennung'],
name:'Unterschrift (freiwillig)',namePlaceholder:'Wie sollen wir dich nennen?',notes:'Abschließende Bemerkungen (freiwillig)',notesPlaceholder:'Ein Satz, eine Kritik, eine übertriebene Analyse …',noIdentity:'Keine persönlichen Daten erforderlich. Alles darf leer bleiben.',optionalConfirm:'Meine Angaben sind einigermaßen ehrlich.',noPledge:'Keine Unterschrift erforderlich. Auch kein Versprechen.',
reportEyebrow:'DOKUMENT ERSTELLT / PRIVAT',reportReady:'BEWERTUNG ABGESCHLOSSEN',scoreLabel:'DURCHSCHNITT',reportSummary:'Zusammenfassung',ratingCount:'Bewertungen',reportCategory:['Interesse','Technische Qualität','Idee und Tempo','Wirkung','Gesamturteil'],verdicts:['Der Ausschuss empfiehlt keine zweite Sichtung.','Es bestehen Bedenken. Niemand wurde informiert.','Akzeptables Ergebnis. Kann archiviert werden.','Ein sehr respektabler Inhalt. Fall geschlossen.','Volle Zustimmung. Die Abteilung ist mäßig beeindruckt.'],whatsapp:'Über WhatsApp teilen ↗',copy:'Bericht kopieren',nativeShare:'Andere Apps',download:'JSON herunterladen',print:'Drucken',preview:'VORSCHAU / BERICHT',noRating:'K. A.',anonymousName:'Nicht angegeben',reportFooter:'Dieses Dokument hat weder Rechtskraft noch einen Existenzgrund.',reportTitle:'CONTENT REVIEW — BERICHT',evaluation:'Bewertung',finalScore:'Durchschnitt',watchedReport:'Ganz angesehen',confirmationReport:'Bestätigung',emotionReport:'Gefühl',commentReport:'Kommentar',nameReport:'Gutachter',notProvided:'Nicht angegeben',shareConfirm:'WhatsApp mit dem Bericht öffnen?',copied:'Bericht kopiert.',failedCopy:'Kopieren fehlgeschlagen. Bitte teilen.',settingsReset:'Optionen zurücksetzen',clearAnswers:'Antworten löschen',resetConfirm:'Alle gespeicherten Antworten löschen?',resetDone:'Antworten gelöscht.',optionsReset:'Optionen zurückgesetzt.',continueFirst:'Bitte zuerst diesen Abschnitt abschließen.',shareError:'Teilen ist hier nicht möglich.',saved:'Lokal gespeichert',instructions:'Alle Optionen sind unabhängig und freiwillig.',keyboardHint:'Tastatur: 1–5 zum Bewerten.',
groups:['Sprache und Aussehen','Barrierefreiheit','Interaktionen','Fragebogen und Datenschutz','Bericht und Teilen'],settings:{language:'Sprache',theme:'Design',vision:'Farbsichtmodus',accent:'Akzentfarbe',largeText:'Größerer Text',highContrast:'Hoher Kontrast',reducedMotion:'Animationen reduzieren',sounds:'Tastentöne',haptics:'Vibration beim Bewerten',saveAnswers:'Antworten lokal speichern',rememberStep:'Letzten Abschnitt merken',showProgress:'Fortschrittsbalken',showHints:'Hinweise zu Fragen',showLegends:'Skalenbeschriftung 1–5',institutionalHumor:'Amtliche Kommentare',compact:'Kompakte Ansicht',readingMode:'Lesemodus',confirmShare:'Teilen bestätigen',includeDate:'Datum im Bericht',detailedReport:'Alle Einzelnoten',showStatistics:'Zusammenfassungsgrafik',anonymous:'Anonymer Bericht',allowSkip:'Unbewertete Fragen erlauben',keyboard:'Tastenkürzel'},choices:{dark:'Dunkel',light:'Hell',system:'System',normal:'Standard',deuter:'Deuteranopie',protan:'Protanopie',tritan:'Tritanopie',classic:'Limette',cobalt:'Blau',peach:'Pfirsich'}},
pt:{
skip:'Ir para a avaliação',settingsShort:'Opções',heroEyebrow:'DEPARTAMENTO DE OPINIÕES NÃO SOLICITADAS · DESDE 2026',heroLine1:'VALEU',heroLine2:'MESMO',heroLine3:'A PENA?',heroDesc:'Recebeste um conteúdo. Chegou a hora de o avaliar com um rigor completamente desnecessário. Cerca de dois minutos.',start:'Começar avaliação',surveyEyebrow:'QUESTIONÁRIO / EDIÇÃO ESPECIAL',surveyTitle:'PARA REGISTO.',surveyAside:'Sem conta. Sem avaliações públicas. Sem motivo real para este processo.',settingsEyebrow:'APENAS PARA QUEM INSISTE',settingsTitle:'DEFINIÇÕES.',savedLocally:'Preferências guardadas apenas neste dispositivo.',done:'Concluído ✓',back:'Voltar',next:'Continuar',strip1:'JUÍZO / PERCEÇÃO',strip2:'DECLARAÇÕES / VEREDITO',strip3:'MUITO SÉRIO (NÃO VERIFICADO)',footerText:'Nenhuma autoridade competente foi consultada.',backHome:'← Voltar ao SwadyaSpace',
stageTitles:['PRIMEIRA IMPRESSÃO.','À LUPA.','MAIS A FUNDO.','NA MEMÓRIA.','A SENTENÇA.','CONTROLO DE QUALIDADE.','ÚLTIMA FORMALIDADE.','O VEREDITO.'],
stageDescriptions:['O essencial. Três notas, sem complicações.','Análise técnica. Levamos isto surpreendentemente a sério.','Originalidade e ritmo. O comité toma notas.','Considerações a médio prazo. Ou sete minutos.','Três perguntas decisivas. Responde sem olhar para o teto.','Estas declarações serão levadas a sério sem razão específica.','O nome é opcional. O conteúdo já foi avaliado.','O comité decidiu. Ninguém sabe quem o nomeou.'],
phase:'SECÇÃO',answers:'RESPOSTAS',protocol:'PROTOCOLO ATIVO',low:'Nada',high:'Muito',questionHint:'Um número. Não são permitidos meios pontos.',missing:'Avalia as três perguntas antes de continuar.',missingOverall:'É necessária pelo menos uma nota.',reportBtn:'Gerar veredito',restart:'Nova avaliação',seen:'Viste mesmo todo o conteúdo?',confirmSeen:'Confirmas a declaração anterior?',emotion:'Sensação predominante',selectAnswer:'Escolhe uma resposta',seenOptions:['Sim, do início ao fim','Quase tudo','Não, mas tenho uma opinião','Não posso confirmar'],confirmOptions:['Confirmo','Confirmo, mas não sob juramento','Prefiro não responder'],emotionOptions:['Diversão','Curiosidade','Confusão','Indiferença','Ligeiro desconforto','Apreciação involuntária'],
name:'Assinatura (opcional)',namePlaceholder:'Como queres ser tratado?',notes:'Observações finais (opcionais)',notesPlaceholder:'Uma frase, uma crítica, uma análise desproporcionada…',noIdentity:'Não são necessários dados pessoais. Podes deixar tudo vazio.',optionalConfirm:'Declaro que as respostas são razoavelmente sinceras.',noPledge:'Não precisas de assinar. Nem de prometer.',
reportEyebrow:'DOCUMENTO GERADO / USO PRIVADO',reportReady:'AVALIAÇÃO CONCLUÍDA',scoreLabel:'MÉDIA',reportSummary:'Resumo do comité',ratingCount:'Notas registadas',reportCategory:['Envolvimento','Qualidade técnica','Ideia e ritmo','Impacto','Juízo final'],verdicts:['O comité não recomenda uma segunda visualização.','Existem algumas reservas. Ninguém foi informado.','Resultado aceitável. Pode ser arquivado.','Um conteúdo bastante respeitável. Caso encerrado.','Aprovação total. O departamento está moderadamente impressionado.'],whatsapp:'Partilhar no WhatsApp ↗',copy:'Copiar relatório',nativeShare:'Outras apps',download:'Transferir JSON',print:'Imprimir',preview:'PRÉ-VISUALIZAÇÃO / RELATÓRIO',noRating:'N/D',anonymousName:'Não declarado',reportFooter:'Este documento não tem validade legal nem motivo para existir.',reportTitle:'CONTENT REVIEW — RELATÓRIO',evaluation:'Nota',finalScore:'Média',watchedReport:'Visualização completa',confirmationReport:'Confirmação',emotionReport:'Sensação',commentReport:'Comentário',nameReport:'Avaliador',notProvided:'Não indicado',shareConfirm:'Abrir o WhatsApp com o relatório?',copied:'Relatório copiado.',failedCopy:'Não foi possível copiar. Tenta partilhar.',settingsReset:'Repor opções',clearAnswers:'Apagar respostas',resetConfirm:'Apagar todas as respostas deste dispositivo?',resetDone:'Respostas apagadas.',optionsReset:'Opções repostas.',continueFirst:'Completa esta secção primeiro.',shareError:'Partilha indisponível neste navegador.',saved:'Guardado localmente',instructions:'Todas as opções são independentes e opcionais.',keyboardHint:'Atalho: teclas 1–5 para avaliar.',
groups:['Idioma e aparência','Acessibilidade','Interações','Questionário e privacidade','Relatório e partilha'],settings:{language:'Idioma',theme:'Tema',vision:'Modo de visão de cores',accent:'Cor de destaque',largeText:'Texto maior',highContrast:'Alto contraste',reducedMotion:'Reduzir animações',sounds:'Sons dos botões',haptics:'Vibrar ao avaliar',saveAnswers:'Guardar respostas localmente',rememberStep:'Lembrar última secção',showProgress:'Barra de progresso',showHints:'Dicas nas perguntas',showLegends:'Escala de 1 a 5',institutionalHumor:'Comentários institucionais',compact:'Vista compacta',readingMode:'Modo leitura',confirmShare:'Confirmar antes de partilhar',includeDate:'Data no relatório',detailedReport:'Lista de todas as notas',showStatistics:'Gráfico resumo',anonymous:'Relatório anónimo',allowSkip:'Permitir perguntas sem nota',keyboard:'Atalhos de teclado'},choices:{dark:'Escuro',light:'Claro',system:'Sistema',normal:'Normal',deuter:'Deuteranopia',protan:'Protanopia',tritan:'Tritanopia',classic:'Lima',cobalt:'Azul',peach:'Pêssego'}},
ja:{
skip:'評価に移動',settingsShort:'設定',heroEyebrow:'頼まれていない意見の部門 · 2026年創立',heroLine1:'本当に',heroLine2:'見る価値',heroLine3:'あった？',heroDesc:'コンテンツが送られてきました。今こそ不必要なほど真剣に評価しましょう。所要時間は約2分。',start:'評価を始める',surveyEyebrow:'特別評価アンケート',surveyTitle:'記録に残そう。',surveyAside:'登録不要。公開評価なし。この手続きに特別な理由もありません。',settingsEyebrow:'こだわる人だけのエリア',settingsTitle:'設定。',savedLocally:'設定はこの端末にのみ保存されます。',done:'完了 ✓',back:'戻る',next:'次へ',strip1:'評価 / 印象',strip2:'申告 / 判定',strip3:'非常に真剣（未確認）',footerText:'関係当局への相談はしていません。',backHome:'← SwadyaSpace に戻る',
stageTitles:['第一印象。','細かくチェック。','さらに深く。','記憶への影響。','最終評価。','品質検査。','最後の手続き。','判定結果。'],
stageDescriptions:['まずは基本の3問です。難しいことはありません。','技術面の評価です。驚くほど真剣です。','独創性とテンポ。委員会はメモ中です。','少し先まで残る印象。少なくともあと7分。','最後の3問です。天井を見ずに答えてください。','これらの申告は理由なく真剣に扱われます。','名前は任意です。評価はすでに完了しています。','委員会が決定しました。誰が任命したかは不明です。'],
phase:'セクション',answers:'回答',protocol:'審査中',low:'まったく',high:'非常に',questionHint:'1～5の整数を選択してください。',missing:'次に進むには3問すべてを評価してください。',missingOverall:'最低1つの評価が必要です。',reportBtn:'判定を作成',restart:'新しい評価',seen:'本当に最後まで見ましたか？',confirmSeen:'先ほどの申告を確認しますか？',emotion:'主な感情',selectAnswer:'選択してください',seenOptions:['はい、最初から最後まで','ほとんど全部','いいえ、でも意見はあります','確認できません'],confirmOptions:['確認します','確認しますが宣誓ではありません','回答を控えます'],emotionOptions:['楽しさ','好奇心','混乱','無関心','軽い不快感','思わぬ好感'],
name:'評価者名（任意）',namePlaceholder:'何とお呼びしましょう？',notes:'最後の感想（任意）',notesPlaceholder:'一言、批評、または大げさな分析を…',noIdentity:'個人情報は不要です。すべて空欄でも構いません。',optionalConfirm:'概ね正直に答えたと宣言します。',noPledge:'署名も約束も不要です。',
reportEyebrow:'作成済み / 個人利用',reportReady:'評価完了',scoreLabel:'平均点',reportSummary:'委員会のまとめ',ratingCount:'記録された評価',reportCategory:['関心','技術的品質','発想とテンポ','印象','総合評価'],verdicts:['委員会は再視聴を推奨しません。','懸念点が見つかりました。誰にも通知していません。','まずまずの結果です。保管可能です。','十分に良い内容です。審査終了。','全面承認。委員会はほどほどに感心しています。'],whatsapp:'WhatsApp で共有 ↗',copy:'レポートをコピー',nativeShare:'他のアプリ',download:'JSONを保存',print:'印刷',preview:'レポートのプレビュー',noRating:'なし',anonymousName:'非公開',reportFooter:'この文書に法的効力も存在意義もありません。',reportTitle:'CONTENT REVIEW — レポート',evaluation:'評価',finalScore:'平均',watchedReport:'最後まで視聴',confirmationReport:'確認',emotionReport:'感情',commentReport:'コメント',nameReport:'評価者',notProvided:'未記入',shareConfirm:'WhatsApp でレポートを開きますか？',copied:'レポートをコピーしました。',failedCopy:'コピーできません。共有してください。',settingsReset:'設定をリセット',clearAnswers:'回答を削除',resetConfirm:'この端末の回答をすべて削除しますか？',resetDone:'回答を削除しました。',optionsReset:'設定を初期化しました。',continueFirst:'このセクションを完了してください。',shareError:'このブラウザでは共有できません。',saved:'端末に保存済み',instructions:'すべての設定は独立していて任意です。',keyboardHint:'ショートカット：1～5キーで評価。',
groups:['言語と見た目','アクセシビリティ','操作','アンケートとプライバシー','レポートと共有'],settings:{language:'表示言語',theme:'テーマ',vision:'色覚モード',accent:'アクセント色',largeText:'文字を大きく',highContrast:'高コントラスト',reducedMotion:'アニメを減らす',sounds:'ボタン音',haptics:'評価時の振動',saveAnswers:'回答を端末に保存',rememberStep:'前回のセクションを記憶',showProgress:'進行状況バー',showHints:'質問のヒント',showLegends:'1～5の説明',institutionalHumor:'公的な冗談',compact:'コンパクト表示',readingMode:'読書モード',confirmShare:'共有前に確認',includeDate:'レポートに日付',detailedReport:'全評価を表示',showStatistics:'集計グラフ',anonymous:'匿名レポート',allowSkip:'未評価を許可',keyboard:'キーボード操作'},choices:{dark:'ダーク',light:'ライト',system:'システム',normal:'標準',deuter:'第二色覚異常',protan:'第一色覚異常',tritan:'第三色覚異常',classic:'ライム',cobalt:'ブルー',peach:'ピーチ'}}
};
const SETTING_GROUPS=[
[{key:'language',values:['it','en','es','zh','fr','de','pt','ja'],labels:['Italiano','English','Español','中文','Français','Deutsch','Português','日本語']},{key:'theme',values:['dark','light','system']},{key:'accent',values:['classic','cobalt','peach']}],
[{key:'vision',values:['normal','deuter','protan','tritan']},'largeText','highContrast','reducedMotion','readingMode'],
['sounds','haptics','keyboard','compact'],
['saveAnswers','rememberStep','showProgress','showHints','showLegends','institutionalHumor','allowSkip'],
['confirmShare','includeDate','detailedReport','showStatistics','anonymous']
];
let prefs={...DEFAULTS};
let state={ratings:Array(15).fill(0),stage:0,watched:'',confirmed:'',emotion:'',name:'',notes:'',pledge:false};
let noticeTimeout=null,modalOpen=false,returnFocus=null,audio=null;
const t=()=>T[prefs.language]||T.it;
const savePref=()=>{try{localStorage.setItem(STORAGE_PREFS,JSON.stringify(prefs))}catch(_){}};
const saveDraft=()=>{try{if(prefs.saveAnswers){const copy={...state,stage:prefs.rememberStep?state.stage:0};localStorage.setItem(STORAGE_DRAFT,JSON.stringify(copy))}else localStorage.removeItem(STORAGE_DRAFT)}catch(_){}};
function restore(){
try{const saved=JSON.parse(localStorage.getItem(STORAGE_PREFS)||'null');if(saved&&typeof saved==='object'){for(const k of Object.keys(DEFAULTS)){if(typeof saved[k]===typeof DEFAULTS[k])prefs[k]=saved[k]}}}catch(_){}
try{const saved=JSON.parse(localStorage.getItem(STORAGE_DRAFT)||'null');if(saved&&prefs.saveAnswers){const clean=Array.isArray(saved.ratings)?saved.ratings.slice(0,15).map(v=>Number.isInteger(v)&&v>=1&&v<=5?v:0):[];state.ratings=Array.from({length:15},(_,i)=>clean[i]||0);for(const k of ['watched','confirmed','emotion','name','notes'])if(typeof saved[k]==='string')state[k]=saved[k].slice(0,k==='notes'?2000:120);state.pledge=!!saved.pledge;state.stage=prefs.rememberStep&&Number.isInteger(saved.stage)?Math.max(0,Math.min(7,saved.stage)):0;}}catch(_){}
}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(noticeTimeout);noticeTimeout=setTimeout(()=>el.classList.remove('show'),2900)}
function applyAppearance(){
const theme=prefs.theme==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):prefs.theme;
Object.entries({theme,vision:prefs.vision,accent:prefs.accent,contrast:String(prefs.highContrast),reduced:String(prefs.reducedMotion),compact:String(prefs.compact),reading:String(prefs.readingMode)}).forEach(([k,v])=>document.body.dataset[k]=v);
document.documentElement.style.setProperty('--fontScale',prefs.largeText?'1.17':'1');
document.querySelector('meta[name="theme-color"]').content=theme==='dark'?'#111418':'#f2f0e8';
$('progressTrack').style.display=prefs.showProgress?'':'none';
}
function syncStatic(){
document.documentElement.lang=prefs.language;
document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(t()[key])el.textContent=t()[key]});
$('settingsOpen').setAttribute('aria-label',t().settingsTitle);
$('settingsClose').setAttribute('aria-label',t().done);
document.title='CONTENT REVIEW / '+t().surveyTitle;
}
function renderSettings(){
const translations=t(),names=translations.settings;
let html='<p style="color:var(--muted);font-size:12px;margin:0 0 15px">'+esc(translations.instructions)+'</p>';
SETTING_GROUPS.forEach((items,i)=>{
html+='<details class="settings-group" '+(i===0?'open':'')+'><summary>'+esc(translations.groups[i])+'</summary>';
items.forEach(item=>{
const key=typeof item==='string'?item:item.key;
html+='<div class="setting-line"><label for="pref-'+key+'">'+esc(names[key])+'</label>';
if(typeof item==='string'){
html+='<label class="switch" aria-label="'+esc(names[key])+'"><input type="checkbox" id="pref-'+key+'" data-pref="'+key+'" '+(prefs[key]?'checked':'')+'><span></span></label>';
}else{
html+='<select id="pref-'+key+'" data-pref="'+key+'" aria-label="'+esc(names[key])+'">';
item.values.forEach((value,j)=>{const label=item.labels?item.labels[j]:translations.choices[value]||value;html+='<option value="'+esc(value)+'" '+(prefs[key]===value?'selected':'')+'>'+esc(label)+'</option>'});
html+='</select>';
}
html+='</div>';
});
html+='</details>';
});
html+='<div class="settings-actions"><button type="button" class="btn" data-action="resetPrefs">'+esc(translations.settingsReset)+'</button><button type="button" class="btn" data-action="clearDraft">'+esc(translations.clearAnswers)+'</button></div>';
$('settingsContent').innerHTML=html;
}
function openSettings(){
if(modalOpen)return;
modalOpen=true;returnFocus=document.activeElement;
renderSettings();$('settingsBackdrop').classList.add('open');$('settingsDialog').classList.add('open');
$('settingsDialog').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';
$('settingsClose').focus();
}
function closeSettings(){
if(!modalOpen)return;modalOpen=false;
$('settingsBackdrop').classList.remove('open');$('settingsDialog').classList.remove('open');$('settingsDialog').setAttribute('aria-hidden','true');document.body.style.overflow='';
if(returnFocus&&returnFocus.focus)returnFocus.focus();
}
function questionHtml(i){
const l=t(),value=state.ratings[i];
return '<article class="question"><div class="q-heading"><span class="q-number">'+String(i+1).padStart(2,'0')+'.</span><div><h3 class="q-name">'+esc(Q[prefs.language][i])+'</h3>'+(prefs.showHints?'<div class="q-hint">'+esc(l.questionHint)+'</div>':'')+'</div></div><div><div class="rating" role="group" aria-label="'+esc(Q[prefs.language][i])+'">'+[1,2,3,4,5].map(n=>'<button type="button" data-rate="'+i+'" data-value="'+n+'" aria-pressed="'+(value===n)+'" aria-label="'+n+' / 5">'+n+'</button>').join('')+'</div>'+(prefs.showLegends?'<div class="rating-legend"><span>'+esc(l.low)+'</span><span>'+esc(l.high)+'</span></div>':'')+'</div></article>';
}
function selectBlock(id,label,arr,value){
return '<div class="field"><label for="'+id+'">'+esc(label)+'</label><select id="'+id+'" data-answer="'+id+'"><option value="">'+esc(t().selectAnswer)+'</option>'+arr.map((x,i)=>'<option value="'+i+'" '+(value===String(i)?'selected':'')+'>'+esc(x)+'</option>').join('')+'</select></div>';
}
function reportData(){
const l=t(),valid=state.ratings.filter(v=>v>0),mean=valid.reduce((a,b)=>a+b,0)/(valid.length||1),groups=[];
for(let i=0;i<5;i++){const slice=state.ratings.slice(i*3,i*3+3).filter(Boolean);groups.push({label:l.reportCategory[i],count:slice.length,mean:slice.length?slice.reduce((a,b)=>a+b,0)/slice.length:0})}
const verdictIndex=Math.min(4,Math.max(0,Math.floor(mean-1+.00001)));
return {average:mean,count:valid.length,verdict:l.verdicts[verdictIndex],groups};
}
function reportText(){
const l=t(),d=reportData(),name=prefs.anonymous?l.anonymousName:state.name.trim()||l.notProvided;
const lines=[l.reportTitle,'────────────────────',l.nameReport+': '+name, ...(prefs.includeDate?[new Date().toLocaleString(prefs.language==='zh'?'zh-CN':prefs.language)]:[]),l.finalScore+': '+d.average.toFixed(2)+' / 5 ('+d.count+'/15)',l.reportSummary+': '+d.verdict];
if(prefs.detailedReport){lines.push('',l.evaluation+':');Q[prefs.language].forEach((q,i)=>lines.push(String(i+1).padStart(2,'0')+'. '+q+': '+(state.ratings[i]?state.ratings[i]+'/5':l.noRating)))}
if(prefs.showStatistics){lines.push('',l.reportSummary+':');d.groups.forEach(g=>lines.push(g.label+': '+(g.count?g.mean.toFixed(2)+'/5':l.noRating)))}
const value=(arr,id)=>state[id]!==''&&arr[Number(state[id])]!==undefined?arr[Number(state[id])]:l.notProvided;
lines.push('',l.watchedReport+': '+value(l.seenOptions,'watched'),l.confirmationReport+': '+value(l.confirmOptions,'confirmed'),l.emotionReport+': '+value(l.emotionOptions,'emotion'),l.commentReport+': '+(state.notes.trim()||l.notProvided),'',l.reportFooter);
return lines.join('\n');
}
function reportHtml(){
const l=t(),d=reportData();
return '<div class="stage-eyebrow">'+esc(l.reportEyebrow)+'</div><h3 class="stage-title">'+esc(l.reportReady)+'</h3><div class="report-score"><div><div class="stage-eyebrow">'+esc(l.scoreLabel)+'</div><div class="score-big">'+d.average.toFixed(2)+'<small>/5</small></div></div><p class="report-verdict">'+esc(d.verdict)+'</p></div><div class="report-meta">'+esc(l.ratingCount)+': '+d.count+'/15 &nbsp; <span class="seal">CONTENT REVIEW / OK</span></div>'+(prefs.showStatistics?'<div><div class="stage-eyebrow">'+esc(l.reportSummary)+'</div>'+d.groups.map(g=>'<div class="chart-row"><span>'+esc(g.label)+'</span><div class="track"><div class="fill" style="width:'+(g.mean/5*100).toFixed(1)+'%"></div></div><strong>'+(g.count?g.mean.toFixed(1):'—')+'</strong></div>').join('')+'</div>':'')+'<div class="report-actions"><button type="button" class="btn primary" data-action="whatsapp">'+esc(l.whatsapp)+'</button><button type="button" class="btn" data-action="copy">'+esc(l.copy)+'</button><button type="button" class="btn" data-action="nativeShare">'+esc(l.nativeShare)+'</button><button type="button" class="btn" data-action="download">'+esc(l.download)+'</button><button type="button" class="btn" data-action="print">'+esc(l.print)+'</button></div>';
}
function render(){
const l=t(),n=state.stage;
syncStatic();applyAppearance();
$('chapterLabel').textContent=l.phase+' '+String(Math.min(7,n+1)).padStart(2,'0')+' / 07';
$('completedLabel').textContent=String(state.ratings.filter(Boolean).length).padStart(2,'0')+' / 15 '+l.answers;
$('progressFill').style.width=Math.min(100,n/7*100)+'%';
$('progressTrack').setAttribute('aria-valuenow',String(Math.round(n/7*100)));
$('pageStatus').textContent=n===7?l.reportReady:l.protocol;
$('previous').style.visibility=n===0?'hidden':'visible';
$('next').style.display=n===7?'none':'inline-flex';
$('next').firstElementChild.textContent=n===6?l.reportBtn:l.next;
const body=$('stageContent');
let html='';
if(n<=4){html='<div class="stage-eyebrow">'+esc(l.phase)+' '+String(n+1).padStart(2,'0')+' / 05</div><h3 class="stage-title">'+esc(l.stageTitles[n])+'</h3><p class="stage-desc">'+esc(l.stageDescriptions[n])+'</p>'+[n*3,n*3+1,n*3+2].map(questionHtml).join('')}
if(n===5)html='<div class="stage-eyebrow">'+esc(l.phase)+' 06 / 07</div><h3 class="stage-title">'+esc(l.stageTitles[n])+'</h3><p class="stage-desc">'+esc(l.stageDescriptions[n])+'</p><div class="two-cols">'+selectBlock('watched',l.seen,l.seenOptions,state.watched)+selectBlock('confirmed',l.confirmSeen,l.confirmOptions,state.confirmed)+'</div>'+selectBlock('emotion',l.emotion,l.emotionOptions,state.emotion)+(prefs.institutionalHumor?'<p class="note-line">'+esc(l.stageDescriptions[5])+'</p>':'');
if(n===6)html='<div class="stage-eyebrow">'+esc(l.phase)+' 07 / 07</div><h3 class="stage-title">'+esc(l.stageTitles[n])+'</h3><p class="stage-desc">'+esc(l.stageDescriptions[n])+'</p><div class="field"><label for="reviewer">'+esc(l.name)+'</label><input id="reviewer" class="input" data-text="name" maxlength="120" placeholder="'+esc(l.namePlaceholder)+'" value="'+esc(state.name)+'"></div><div class="field"><label for="notes">'+esc(l.notes)+'</label><textarea id="notes" data-text="notes" maxlength="2000" placeholder="'+esc(l.notesPlaceholder)+'">'+esc(state.notes)+'</textarea></div><p class="note-line">'+esc(l.noIdentity)+'</p><label class="checkline"><input type="checkbox" data-check="pledge" '+(state.pledge?'checked':'')+'><span>'+esc(l.optionalConfirm)+'</span></label>';
if(n===7)html=reportHtml();
body.innerHTML=html;
}
function goTo(stage,scroll=true){state.stage=Math.max(0,Math.min(7,stage));render();saveDraft();if(scroll&&prefs.rememberStep!==null){$('survey').scrollIntoView({behavior:prefs.reducedMotion?'auto':'smooth',block:'start'})}}
function next(){
if(state.stage<=4&&!prefs.allowSkip){const first=state.stage*3;if(state.ratings.slice(first,first+3).some(x=>x===0)){toast(t().missing);const b=$('stageContent').querySelector('.rating button[aria-pressed="false"]');if(b)b.focus();return}}
if(state.stage===6&&!state.ratings.some(Boolean)){toast(t().missingOverall);return}
if(state.stage<7){playTone();goTo(state.stage+1)}
}
function playTone(){if(!prefs.sounds)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;if(!audio)audio=new C();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=610;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.06);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.07)}catch(_){}}
function resetDraft(){state={ratings:Array(15).fill(0),stage:0,watched:'',confirmed:'',emotion:'',name:'',notes:'',pledge:false};try{localStorage.removeItem(STORAGE_DRAFT)}catch(_){}render()}
function applyPref(key,value){
if(!(key in DEFAULTS))return;
prefs[key]=value;
if(key==='saveAnswers'&&!value){try{localStorage.removeItem(STORAGE_DRAFT)}catch(_){}}
if(key==='rememberStep'&&!value)saveDraft();
savePref();applyAppearance();
if(key==='language'){renderSettings();render();return}
if(key==='theme'||key==='vision'||key==='accent'||key==='largeText'||key==='highContrast'||key==='reducedMotion')return;
render();
}
async function copyReport(){
try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(reportText());toast(t().copied);return}
const area=document.createElement('textarea');area.value=reportText();area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();const ok=document.execCommand('copy');area.remove();toast(ok?t().copied:t().failedCopy)}catch(_){toast(t().failedCopy)}
}
function download(){
const info={app:'CONTENT REVIEW',version:4,exportedAt:new Date().toISOString(),language:prefs.language,...state,average:reportData().average,report:reportText()};
const blob=new Blob([JSON.stringify(info,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='content-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);
}
function whatsapp(){
if(prefs.confirmShare&&!confirm(t().shareConfirm))return;
const url='https://api.whatsapp.com/send?text='+encodeURIComponent(reportText());
const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';document.body.appendChild(a);a.click();a.remove();
}
async function nativeShare(){
if(!navigator.share){await copyReport();return}
try{await navigator.share({title:'CONTENT REVIEW',text:reportText()})}catch(e){if(e.name!=='AbortError')toast(t().shareError)}
}
function onAction(name){
switch(name){
case 'whatsapp':whatsapp();break;
case 'copy':copyReport();break;
case 'nativeShare':nativeShare();break;
case 'download':download();break;
case 'print':window.print();break;
case 'resetPrefs':if(confirm(t().settingsReset+'?')){prefs={...DEFAULTS};savePref();applyAppearance();renderSettings();render();toast(t().optionsReset)}break;
case 'clearDraft':if(confirm(t().resetConfirm)){resetDraft();toast(t().resetDone);closeSettings()}break;
}}
restore();render();
$('startButton').addEventListener('click',()=>{$('survey').scrollIntoView({behavior:prefs.reducedMotion?'auto':'smooth'});});
$('settingsOpen').addEventListener('click',openSettings);
$('settingsClose').addEventListener('click',closeSettings);
$('settingsDone').addEventListener('click',closeSettings);
$('settingsBackdrop').addEventListener('click',closeSettings);
$('next').addEventListener('click',next);
$('previous').addEventListener('click',()=>goTo(state.stage-1));
$('settingsContent').addEventListener('change',e=>{
const node=e.target.closest('[data-pref]');if(!node)return;const key=node.dataset.pref;
applyPref(key,node.type==='checkbox'?node.checked:node.value);
});
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action)onAction(action.dataset.action);
const rating=e.target.closest('[data-rate]');if(!rating)return;const i=Number(rating.dataset.rate),n=Number(rating.dataset.value);if(i<0||i>=15)return;state.ratings[i]=n;playTone();if(prefs.haptics&&navigator.vibrate)navigator.vibrate(13);render();saveDraft();});
$('stageContent').addEventListener('change',e=>{
const select=e.target.closest('[data-answer]');if(select){const key=select.dataset.answer;if(key==='watched')state.watched=select.value;if(key==='confirmed')state.confirmed=select.value;if(key==='emotion')state.emotion=select.value;saveDraft()}
const box=e.target.closest('[data-check]');if(box){state.pledge=box.checked;saveDraft()}
});
$('stageContent').addEventListener('input',e=>{const node=e.target.closest('[data-text]');if(node){state[node.dataset.text]=node.value;saveDraft()}});
document.addEventListener('keydown',e=>{
if(e.key==='Escape'&&modalOpen){closeSettings();return}
if(modalOpen&&e.key==='Tab'){
const focusable=Array.from($('settingsDialog').querySelectorAll('button,input,select,summary')).filter(x=>x.getClientRects().length);
if(focusable.length){const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}return;
}
if(!prefs.keyboard||state.stage>4||e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName))return;
if(/^[1-5]$/.test(e.key)){const start=state.stage*3,index=state.ratings.slice(start,start+3).findIndex(v=>v===0);if(index>=0){state.ratings[start+index]=Number(e.key);render();saveDraft();}}
});
const mm=window.matchMedia&&window.matchMedia('(prefers-color-scheme: light)');
if(mm&&mm.addEventListener)mm.addEventListener('change',()=>{if(prefs.theme==='system')applyAppearance()});
})();